document.write('<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n');
document.write('        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n');
document.write('            <span class=\"navbar-toggler-icon\"></span>\n');
document.write('        </button> <a class=\"navbar-brand\" href=\"#\">POE小幫手</a>\n');
document.write('        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n');
document.write('            <ul class=\"navbar-nav\">\n');
document.write('                <li class=\"nav-item\">\n');
document.write('                    <a class=\"nav-link\" href=\"shopFilter.html\">商店篩選器</a>\n');
document.write('                </li>\n');
document.write('                <li class=\"nav-item\">\n');
document.write('                    <a class=\"nav-link\" href=\"stashFilter.html\">倉庫篩選器</a>\n');
document.write('                </li>\n');
document.write('                <li class=\"nav-item\">\n');
document.write('                    <a class=\"nav-link\" href=\"https://www.filterblade.xyz/\">filterblade</a>\n');
document.write('                </li>\n');
document.write('                <li class=\"nav-item dropdown\">\n');
document.write('                    <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdownMenuLink\" data-bs-toggle=\"dropdown\">外部連結</a>\n');
document.write('                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://www.pathofexile.com/\">POE官網</a>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://poe.ninja/builds/ancestor\">Ninja - Builds</a>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://poedb.tw/tw/chinese\">poedb中文化</a>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://poedb.tw/tw/Modifiers\">poedb詞綴表</a>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://forum.gamer.com.tw/B.php?bsn=18966\">巴哈POE版</a>\n');
document.write('                        <div class=\"dropdown-divider\"></div>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://github.com/lemasatodev/POE-Trades-Companion\">POE-Trades-Companion</a>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://github.com/SnosMe/awakened-poe-trade\">awakened-poe-trade</a>\n');
document.write('                        <div class=\"dropdown-divider\"></div>\n');
document.write('                        <a class=\"dropdown-item\" href=\"https://poe.re/#/maps\">Regex - Map Modifiers</a>\n');
document.write('                    </div>\n');
document.write('                </li>\n');
document.write('            </ul>\n');
document.write('        </div>\n');
document.write('    </nav>');